[package]
name = "label_space"
version = "0.1.0"
authors = ["mxx307 <mxx307slq@gmail.com>"]
edition = "2024"

[dependencies]
ctrlc = "3.4.5"
eframe = "0.31.0"
egui = "0.31.0"
image = "0.25.5"
rand = "0.9.0"
rfd = "0.15.2"
